Description: Development EC2 instance for Bryan
Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      Name: bryan-dev
      Subnets:
        - subnet-03b6bc61 # us-west-2a
        - subnet-ff77438b # us-west-2b
        - subnet-21a0f767 # us-west-2c
      SecurityGroups:
        - sg-05cd913205a3f1a83
      Tags:
        - Key: owner
          Value: bryan.kao
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTPS
      Port: 443
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      Certificates:
        - CertificateArn: arn:aws:acm:us-west-2:945568539318:certificate/287ba503-8050-4ac9-91fa-fd65e2790207 # *.gazebo.works
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: bryan-dev
      ProtocolVersion: HTTP1
      HealthCheckPath: /healthcheck
      HealthCheckTimeoutSeconds: 5
      VpcId: vpc-33aabf51 # default VPC
      Tags:
        - Key: owner
          Value: bryan.kao