Description: Development EC2 instance for Bryan
Outputs:
  PublicIpEc2:
    Description: Public IP of EC2 instance
    Value: !GetAtt ec2.PublicIp
  DNSAlb:
    Description: DNS Name of ALB
    Value: !Join [ "", ["https://", !Ref Route53Alb] ]
Resources:
  ec2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.large
      KeyName: bryan-dev
      LaunchTemplate:
        LaunchTemplateId: lt-06819c1d1cd23ae51 # dev-box-al2023-large
        Version: 1
      UserData:
        Fn::Base64: |
          #!/bin/bash

          ##### as root
          ## working directory
          mkdir -p /var/cascade
          chown ec2-user /var/cascade

          ## git
          dnf install -y git

          ## gh cli
          type -p yum-config-manager >/dev/null || yum install yum-utils
          yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          yum install -y gh

          ##### change to ec2-user
          sudo -i -u ec2-user bash << EOF
          ## nvm
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

          ## enable use of nvm in current session
          source /home/ec2-user/.bashrc

          ## install node
          nvm install 18

          ## configure npm
          npm config set legacy-peer-deps=true

          ## configure git
          echo .DS_Store > ~/.gitignore_global
          git config --global core.excludesfile ~/.gitignore_global
          git config --global user.name "Bryan Kao"
          git config --global user.email "bryan.kao@cascadeenergy.com"

          ## symlink the cascade folder
          ln -s /var/cascade
          EOF
      Tags:
        - Key: Name
          Value: bryan-dev
        - Key: owner
          Value: bryan.kao
  # Route53Ec2:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     Type: A
  #     HostedZoneId: Z0902760TYAHV8SW0EEY # gazebo.works
  #     Name: developer-bryan.gazebo.works
  #     TTL: 300
  #     ResourceRecords:
  #       - !Ref ElasticIPEc2
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      Name: bryan-dev
      Subnets:
        - subnet-03b6bc61 # us-west-2a
        - subnet-ff77438b # us-west-2b
        - subnet-21a0f767 # us-west-2c
      SecurityGroups:
        - sg-05cd913205a3f1a83
      Tags:
        - Key: owner
          Value: bryan.kao
  Route53Alb:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: Zone apex alias targeted to ALB
      HostedZoneId: Z0902760TYAHV8SW0EEY # gazebo.works
      Name: dev-bryan.gazebo.works
      Type: A
      AliasTarget: 
        HostedZoneId: !GetAtt ALB.CanonicalHostedZoneID
        DNSName: !GetAtt ALB.DNSName
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTPS
      Port: 443
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      Certificates:
        - CertificateArn: arn:aws:acm:us-west-2:945568539318:certificate/287ba503-8050-4ac9-91fa-fd65e2790207 # *.gazebo.works
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: bryan-dev
      ProtocolVersion: HTTP1
      HealthCheckPath: /healthcheck
      HealthCheckTimeoutSeconds: 5
      VpcId: vpc-33aabf51 # default VPC
      Targets:
        - Id: !Ref ec2
          Port: 9101
      Tags:
        - Key: owner
          Value: bryan.kao
